// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Order is the predicate function for order builders.
type Order func(*sql.Selector)

// OrderItem is the predicate function for orderitem builders.
type OrderItem func(*sql.Selector)

// Refund is the predicate function for refund builders.
type Refund func(*sql.Selector)
