services:
  asp-user:
    image: asp-user
    build:
      context: .
      dockerfile: asp-user/Dockerfile
    ports:
        - "5232:5232"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
  
  nest-api-gateway-auth:
    image: nest-api-gateway-auth
    build:
      context: .
      dockerfile: nest-api-gateway-auth/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - asp-user

  spring-boot-post:
    image: spring-boot-post
    build:
      context: .
      dockerfile: spring-boot-post/Dockerfile
    ports:
      - "2003:2003"
    
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
    
volumes:
  cache: