// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.example.stock
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// Event emitted after a stock reduction is successful
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class StockReductionFailedEvent : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"StockReductionFailedEvent\",\"doc\":\"Event emitted after a " +
				"stock reduction is successful\",\"namespace\":\"com.example.stock\",\"fields\":[{\"name\"" +
				":\"order_id\",\"type\":\"string\"},{\"name\":\"message\",\"type\":\"string\"}]}");
		private string _order_id;
		private string _message;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return StockReductionFailedEvent._SCHEMA;
			}
		}
		public string order_id
		{
			get
			{
				return this._order_id;
			}
			set
			{
				this._order_id = value;
			}
		}
		public string message
		{
			get
			{
				return this._message;
			}
			set
			{
				this._message = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.order_id;
			case 1: return this.message;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.order_id = (System.String)fieldValue; break;
			case 1: this.message = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
