// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"golang-order/ent/order"
	"golang-order/ent/orderitem"
	"golang-order/ent/refund"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// RefundCreate is the builder for creating a Refund entity.
type RefundCreate struct {
	config
	mutation *RefundMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (rc *RefundCreate) SetCreatedAt(t time.Time) *RefundCreate {
	rc.mutation.SetCreatedAt(t)
	return rc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (rc *RefundCreate) SetNillableCreatedAt(t *time.Time) *RefundCreate {
	if t != nil {
		rc.SetCreatedAt(*t)
	}
	return rc
}

// SetUpdatedAt sets the "updated_at" field.
func (rc *RefundCreate) SetUpdatedAt(t time.Time) *RefundCreate {
	rc.mutation.SetUpdatedAt(t)
	return rc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (rc *RefundCreate) SetNillableUpdatedAt(t *time.Time) *RefundCreate {
	if t != nil {
		rc.SetUpdatedAt(*t)
	}
	return rc
}

// SetStatus sets the "status" field.
func (rc *RefundCreate) SetStatus(r refund.Status) *RefundCreate {
	rc.mutation.SetStatus(r)
	return rc
}

// SetAmount sets the "amount" field.
func (rc *RefundCreate) SetAmount(f float64) *RefundCreate {
	rc.mutation.SetAmount(f)
	return rc
}

// SetReason sets the "reason" field.
func (rc *RefundCreate) SetReason(s string) *RefundCreate {
	rc.mutation.SetReason(s)
	return rc
}

// SetPaymentRefundID sets the "payment_refund_id" field.
func (rc *RefundCreate) SetPaymentRefundID(u uuid.UUID) *RefundCreate {
	rc.mutation.SetPaymentRefundID(u)
	return rc
}

// SetNillablePaymentRefundID sets the "payment_refund_id" field if the given value is not nil.
func (rc *RefundCreate) SetNillablePaymentRefundID(u *uuid.UUID) *RefundCreate {
	if u != nil {
		rc.SetPaymentRefundID(*u)
	}
	return rc
}

// SetID sets the "id" field.
func (rc *RefundCreate) SetID(u uuid.UUID) *RefundCreate {
	rc.mutation.SetID(u)
	return rc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (rc *RefundCreate) SetNillableID(u *uuid.UUID) *RefundCreate {
	if u != nil {
		rc.SetID(*u)
	}
	return rc
}

// SetOrderID sets the "order" edge to the Order entity by ID.
func (rc *RefundCreate) SetOrderID(id uuid.UUID) *RefundCreate {
	rc.mutation.SetOrderID(id)
	return rc
}

// SetNillableOrderID sets the "order" edge to the Order entity by ID if the given value is not nil.
func (rc *RefundCreate) SetNillableOrderID(id *uuid.UUID) *RefundCreate {
	if id != nil {
		rc = rc.SetOrderID(*id)
	}
	return rc
}

// SetOrder sets the "order" edge to the Order entity.
func (rc *RefundCreate) SetOrder(o *Order) *RefundCreate {
	return rc.SetOrderID(o.ID)
}

// AddItemIDs adds the "items" edge to the OrderItem entity by IDs.
func (rc *RefundCreate) AddItemIDs(ids ...uuid.UUID) *RefundCreate {
	rc.mutation.AddItemIDs(ids...)
	return rc
}

// AddItems adds the "items" edges to the OrderItem entity.
func (rc *RefundCreate) AddItems(o ...*OrderItem) *RefundCreate {
	ids := make([]uuid.UUID, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return rc.AddItemIDs(ids...)
}

// Mutation returns the RefundMutation object of the builder.
func (rc *RefundCreate) Mutation() *RefundMutation {
	return rc.mutation
}

// Save creates the Refund in the database.
func (rc *RefundCreate) Save(ctx context.Context) (*Refund, error) {
	rc.defaults()
	return withHooks(ctx, rc.sqlSave, rc.mutation, rc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rc *RefundCreate) SaveX(ctx context.Context) *Refund {
	v, err := rc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rc *RefundCreate) Exec(ctx context.Context) error {
	_, err := rc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rc *RefundCreate) ExecX(ctx context.Context) {
	if err := rc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rc *RefundCreate) defaults() {
	if _, ok := rc.mutation.CreatedAt(); !ok {
		v := refund.DefaultCreatedAt()
		rc.mutation.SetCreatedAt(v)
	}
	if _, ok := rc.mutation.UpdatedAt(); !ok {
		v := refund.DefaultUpdatedAt()
		rc.mutation.SetUpdatedAt(v)
	}
	if _, ok := rc.mutation.ID(); !ok {
		v := refund.DefaultID()
		rc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rc *RefundCreate) check() error {
	if _, ok := rc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Refund.created_at"`)}
	}
	if _, ok := rc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Refund.updated_at"`)}
	}
	if _, ok := rc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Refund.status"`)}
	}
	if v, ok := rc.mutation.Status(); ok {
		if err := refund.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Refund.status": %w`, err)}
		}
	}
	if _, ok := rc.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "Refund.amount"`)}
	}
	if v, ok := rc.mutation.Amount(); ok {
		if err := refund.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "Refund.amount": %w`, err)}
		}
	}
	if _, ok := rc.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`ent: missing required field "Refund.reason"`)}
	}
	return nil
}

func (rc *RefundCreate) sqlSave(ctx context.Context) (*Refund, error) {
	if err := rc.check(); err != nil {
		return nil, err
	}
	_node, _spec := rc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	rc.mutation.id = &_node.ID
	rc.mutation.done = true
	return _node, nil
}

func (rc *RefundCreate) createSpec() (*Refund, *sqlgraph.CreateSpec) {
	var (
		_node = &Refund{config: rc.config}
		_spec = sqlgraph.NewCreateSpec(refund.Table, sqlgraph.NewFieldSpec(refund.FieldID, field.TypeUUID))
	)
	if id, ok := rc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := rc.mutation.CreatedAt(); ok {
		_spec.SetField(refund.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := rc.mutation.UpdatedAt(); ok {
		_spec.SetField(refund.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := rc.mutation.Status(); ok {
		_spec.SetField(refund.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := rc.mutation.Amount(); ok {
		_spec.SetField(refund.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := rc.mutation.Reason(); ok {
		_spec.SetField(refund.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := rc.mutation.PaymentRefundID(); ok {
		_spec.SetField(refund.FieldPaymentRefundID, field.TypeUUID, value)
		_node.PaymentRefundID = value
	}
	if nodes := rc.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   refund.OrderTable,
			Columns: []string{refund.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.order_refunds = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := rc.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   refund.ItemsTable,
			Columns: []string{refund.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RefundCreateBulk is the builder for creating many Refund entities in bulk.
type RefundCreateBulk struct {
	config
	err      error
	builders []*RefundCreate
}

// Save creates the Refund entities in the database.
func (rcb *RefundCreateBulk) Save(ctx context.Context) ([]*Refund, error) {
	if rcb.err != nil {
		return nil, rcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(rcb.builders))
	nodes := make([]*Refund, len(rcb.builders))
	mutators := make([]Mutator, len(rcb.builders))
	for i := range rcb.builders {
		func(i int, root context.Context) {
			builder := rcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RefundMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rcb *RefundCreateBulk) SaveX(ctx context.Context) []*Refund {
	v, err := rcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rcb *RefundCreateBulk) Exec(ctx context.Context) error {
	_, err := rcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rcb *RefundCreateBulk) ExecX(ctx context.Context) {
	if err := rcb.Exec(ctx); err != nil {
		panic(err)
	}
}
