version: '3.8'

services:
  asp-user:
    image: asp-user
    build:
      context: ../
      dockerfile: asp-user/Dockerfile
    ports:
      - "5232:5232"
    networks:
      - nest-api-gateway
  
  spring-boot-product:
    image: spring-boot-product
    build:
      context: ../
      dockerfile: spring-boot-product/Dockerfile
    ports:
      - "9090:9090"
    networks:
      - nest-api-gateway

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local

networks:
  nest-api-gateway:
    driver: bridge