// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.example.order
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class Item : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"Item\",\"namespace\":\"com.example.order\",\"fields\":[{\"name\":" +
				"\"variant_id\",\"type\":\"string\"},{\"name\":\"quantity\",\"type\":\"int\"},{\"name\":\"unit_pri" +
				"ce\",\"type\":\"double\"}]}");
		private string _variant_id;
		private int _quantity;
		private double _unit_price;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return Item._SCHEMA;
			}
		}
		public string variant_id
		{
			get
			{
				return this._variant_id;
			}
			set
			{
				this._variant_id = value;
			}
		}
		public int quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				this._quantity = value;
			}
		}
		public double unit_price
		{
			get
			{
				return this._unit_price;
			}
			set
			{
				this._unit_price = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.variant_id;
			case 1: return this.quantity;
			case 2: return this.unit_price;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.variant_id = (System.String)fieldValue; break;
			case 1: this.quantity = (System.Int32)fieldValue; break;
			case 2: this.unit_price = (System.Double)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
