// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.example.order
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class OrderCreatedEvent : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""OrderCreatedEvent"",""namespace"":""com.example.order"",""fields"":[{""name"":""order_id"",""type"":""string""},{""name"":""status"",""type"":""string""},{""name"":""temporary_price"",""type"":""double""},{""name"":""customer_id"",""type"":""string""},{""name"":""items"",""type"":{""type"":""array"",""items"":{""type"":""record"",""name"":""Item"",""namespace"":""com.example.order"",""fields"":[{""name"":""variant_id"",""type"":""string""},{""name"":""quantity"",""type"":""int""},{""name"":""unit_price"",""type"":""double""}]}}}]}");
		private string _order_id;
		private string _status;
		private double _temporary_price;
		private string _customer_id;
		private IList<com.example.order.Item> _items;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return OrderCreatedEvent._SCHEMA;
			}
		}
		public string order_id
		{
			get
			{
				return this._order_id;
			}
			set
			{
				this._order_id = value;
			}
		}
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				this._status = value;
			}
		}
		public double temporary_price
		{
			get
			{
				return this._temporary_price;
			}
			set
			{
				this._temporary_price = value;
			}
		}
		public string customer_id
		{
			get
			{
				return this._customer_id;
			}
			set
			{
				this._customer_id = value;
			}
		}
		public IList<com.example.order.Item> items
		{
			get
			{
				return this._items;
			}
			set
			{
				this._items = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.order_id;
			case 1: return this.status;
			case 2: return this.temporary_price;
			case 3: return this.customer_id;
			case 4: return this.items;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.order_id = (System.String)fieldValue; break;
			case 1: this.status = (System.String)fieldValue; break;
			case 2: this.temporary_price = (System.Double)fieldValue; break;
			case 3: this.customer_id = (System.String)fieldValue; break;
			case 4: this.items = (IList<com.example.order.Item>)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
